#!/usr/bin/env python

"""Summarize some basic stats of a given sequence file"""

import sys
import argparse

from Bio import SeqIO

AP = argparse.ArgumentParser()
AP.add_argument('infile', default=sys.stdin,
                type=argparse.FileType('r'), help="Input a sequence file.")
AP.add_argument('-f', '--format', default='fasta', dest='format',
                help="sequence file format.")
args = AP.parse_args()

def print_seq_stat(args):
    seq_recs = SeqIO.parse(args.infile, args.format)
    print "SeqID\tSeqLen\n--------------------"
    for i in seq_recs:
        print "%s\t%s" % (i.id, len(i.seq))

if __name__ == "__main__":
    print_seq_stat(args)

